name: CI/CD Pipeline with Docker Swarm Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

      - name: Transfer .env file to EC2 Manager
        run: |
          scp -o StrictHostKeyChecking=no .env ec2-user@ec2-35-180-230-219.eu-west-3.compute.amazonaws.com:~/

      - name: Transfer docker-compose.yml to EC2 Manager
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@ec2-35-180-230-219.eu-west-3.compute.amazonaws.com:~/

      - name: Deploy to Docker Swarm Manager
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-35-180-230-219.eu-west-3.compute.amazonaws.com '
            docker stack deploy --compose-file ~/docker-compose.yml forumsebastiengosselin
          '

      - name: Verify deployment
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-35-180-230-219.eu-west-3.compute.amazonaws.com '
            docker service ls
          '
